FROM python:3.11-slim

WORKDIR /app
COPY management_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY management_app/ .

EXPOSE 8600
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8600"]
