import { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import type { Role, User } from "@spas/contracts";
import "./styles.css";

type Section = { id: number; course_code: string; title: string; room: string; weekday: number; period: number };
const api = async <T,>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(path, init); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.error ?? "Request failed"); return body as T; };
const capture = (video: HTMLVideoElement): Promise<Blob> => new Promise((resolve, reject) => { const canvas = document.createElement("canvas"); if (!video.videoWidth) return reject(new Error("Camera is not ready")); canvas.width = video.videoWidth; canvas.height = video.videoHeight; const context = canvas.getContext("2d")!; context.drawImage(video, 0, 0); canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("Cannot capture frame")), "image/jpeg", 0.9); });
const weekdays = ["Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy", "Chủ nhật"];
const periods = [[1, "07:00", "07:50"], [2, "07:55", "08:45"], [3, "08:50", "09:40"], [4, "09:50", "10:40"], [5, "10:45", "11:35"], [6, "11:40", "12:30"], [7, "13:30", "14:20"], [8, "14:25", "15:15"], [9, "15:20", "16:10"], [10, "16:20", "17:10"], [11, "17:15", "18:05"], [12, "18:20", "19:10"], [13, "19:15", "20:05"]] as const;

function Camera({ onReady }: { onReady: (video: HTMLVideoElement) => void }) { const reference = useRef<HTMLVideoElement>(null); useEffect(() => { const video = reference.current!; navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }).then((stream) => { video.srcObject = stream; onReady(video); }).catch(() => undefined); return () => { (video.srcObject as MediaStream | null)?.getTracks().forEach((track) => track.stop()); }; }, [onReady]); return <video className="camera" ref={reference} autoPlay muted playsInline />; }

function Student({ sections }: { sections: Section[] }) { const [video, setVideo] = useState<HTMLVideoElement>(); const [message, setMessage] = useState("Chụp 8 ảnh theo hướng dẫn: thẳng, trái, phải, thẳng."); const enroll = async () => { if (!video) return; try { setMessage("Đang chụp và gửi AI..."); const form = new FormData(); for (let index = 0; index < 8; index += 1) { form.append("frames", await capture(video), `frame-${index}.jpg`); await new Promise((resolve) => setTimeout(resolve, 550)); } await api("/api/face/enrollment", { method: "POST", body: form }); setMessage("Đăng ký khuôn mặt thành công. Admin mới có thể reset."); } catch (error) { setMessage(error instanceof Error ? error.message : "Enrollment failed"); } };
  return <><section className="card"><h2>Đăng ký khuôn mặt</h2><Camera onReady={setVideo} /><button onClick={enroll}>Bắt đầu enrollment</button><p>{message}</p></section><Timetable title="Thời khóa biểu học" sections={sections} /></>;
}

function Teacher({ sections }: { sections: Section[] }) { const [selected, setSelected] = useState<Section>(); const [video, setVideo] = useState<HTMLVideoElement>(); const [message, setMessage] = useState("Chọn một tiết trong thời khóa biểu rồi quét camera."); const scan = async () => { if (!video || !selected) return; try { const form = new FormData(); form.append("image", await capture(video), "classroom.jpg"); const result = await api<{ faces: number; markedIds: string[] }>(`/api/sections/${selected.id}/recognize`, { method: "POST", body: form }); setMessage(`Thấy ${result.faces} khuôn mặt; cập nhật: ${result.markedIds.join(", ") || "không có"}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Scan failed"); } };
  return <><Timetable title="Thời khóa biểu giảng dạy" sections={sections} onSelect={setSelected} selectedId={selected?.id} /><section className="card"><h2>{selected ? `${selected.course_code} · quét điểm danh` : "Chọn tiết để quét"}</h2><Camera onReady={setVideo} /><button disabled={!selected || !video} onClick={scan}>Quét điểm danh</button><p>{message}</p></section></>;
}

function Timetable({ sections, title, onSelect, selectedId }: { sections: Section[]; title: string; onSelect?: (section: Section) => void; selectedId?: number }) { return <section className="card timetable-card"><h2>{title}</h2><div className="timetable"><div className="timetable-head">Ca học</div>{weekdays.map((weekday) => <div className="timetable-head" key={weekday}>{weekday}</div>)}{periods.map(([period, start, end]) => <div className="timetable-row" key={period}><div className="period-cell"><strong>Ca {period}</strong><small>{start}–{end}</small></div>{weekdays.map((weekday, weekdayIndex) => { const section = sections.find((item) => item.weekday === weekdayIndex && item.period === period); if (!section) return <div className="timetable-cell" key={weekday} />; const details = <><strong>{section.course_code}</strong><span>{section.title}</span><small>{section.room}</small></>; return <div className="timetable-cell" key={weekday}>{onSelect ? <button type="button" className={`schedule-item ${selectedId === section.id ? "is-selected" : ""}`} aria-pressed={selectedId === section.id} onClick={() => onSelect(section)}>{details}</button> : <article className="schedule-item">{details}</article>}</div>; })}</div>)}</div></section>; }

function Login({ onLogin }: { onLogin: (user: User) => void }) { const [userId, setUserId] = useState("SV001"); const [password, setPassword] = useState("sv123"); const [error, setError] = useState(""); const login = async (event: React.FormEvent) => { event.preventDefault(); try { const data = await api<{ user: User }>("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, password }) }); onLogin(data.user); } catch (cause) { setError(cause instanceof Error ? cause.message : "Login failed"); } }; return <main className="login"><form className="card" onSubmit={login}><p className="eyebrow">SPAS</p><h1>Điểm danh AI</h1><input value={userId} onChange={(event) => setUserId(event.target.value)} placeholder="Mã tài khoản" /><input value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="Mật khẩu" /><button>Đăng nhập</button><small>Demo: SV001/sv123 · GV001/gv123 · ADMIN001/admin123</small><p className="error">{error}</p></form></main>; }

function App() { const [user, setUser] = useState<User>(); const [sections, setSections] = useState<Section[]>([]); const load = async (current: User) => { const data = await api<{ sections: Section[] }>("/api/sections"); setUser(current); setSections(data.sections); }; useEffect(() => { api<{ user: User }>("/api/auth/me").then((data) => load(data.user)).catch(() => undefined); }, []); if (!user) return <Login onLogin={load} />; const logout = async () => { await api("/api/auth/logout", { method: "POST" }); setUser(undefined); setSections([]); }; return <main className="shell"><header><div><b>SPAS</b><span> · {user.fullName}</span></div><button className="secondary" onClick={logout}>Đăng xuất</button></header><div className="content">{user.role === "student" ? <Student sections={sections} /> : user.role === "teacher" ? <Teacher sections={sections} /> : <Timetable title="Thời khóa biểu toàn trường" sections={sections} />}</div></main>; }

createRoot(document.getElementById("root")!).render(<App />);
